[project]
authors = [{name = "Mahdi Lamb", email = "mahdilamb@gmail.com"}]
dependencies = []
name = "advent-of-code"
version = "2023.12.02"
[tool.setuptools.package-dir]
"advent-of-code" = "."
[project.optional-dependencies]
all = ["advent-of-code[dev]"]
dev = [
  "ruff",
  "pytest",
]
