name: QC and Test
on: 
    push:
    pull_request:
        
jobs:
    qc:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
          - uses: actions/setup-python@v2
            with:
                python-version: '3.11'
                cache: 'pip'
                cache-dependency-path: '**/pyproject.toml'
          - run: pip install .[all]
          - run: pytest --cov=advent_of_code --cov-report term-missing
          - run: ruff check advent_of_code
